#Toolhead Board MCU
[toolhead_h36]
klipper_section: mcu H36Can
action_command: ~/klippy-env/bin/python3 ~/katapult/scripts/flashtool.py -u dcfc08b5ac16

#---------------------------------------------------
#EMU MCUs
[emu_0]
klipper_section: mcu emu_0
action_command: ~/klippy-env/bin/python3 ~/katapult/scripts/flashtool.py -u 5b2d839e328c

[emu_1]
klipper_section: mcu emu_1
action_command: ~/klippy-env/bin/python3 ~/katapult/scripts/flashtool.py -u 5e46d5e0a7d3

[emu_2]
klipper_section: mcu emu_2
action_command: ~/klippy-env/bin/python3 ~/katapult/scripts/flashtool.py -u 7b57bf2d7e02

[emu_3]
klipper_section: mcu emu_3
action_command: ~/klippy-env/bin/python3 ~/katapult/scripts/flashtool.py -u bf0bb8a5c47e

[emu_4]
klipper_section: mcu emu_4
action_command: ~/klippy-env/bin/python3 ~/katapult/scripts/flashtool.py -u 482285150e5d

#---------------------------------------------------
#Main MCU
[m8p_usb2can]
klipper_section: mcu
quiet_command: ~/klippy-env/bin/python3 ~/katapult/scripts/flashtool.py -i can0 -r -u de52e6fc892c; sleep 2
action_command: ~/klippy-env/bin/python3 ~/katapult/scripts/flashtool.py -d /dev/serial/by-id/usb-katapult_stm32h723xx_2F0005001751333031373837-if00
