
#Main MCU
[m8p_usb2can]
klipper_section: mcu
quiet_command: ~/klippy-env/bin/python3 ~/katapult/scripts/flashtool.py -i can0 -r -u de52e6fc892c; sleep 2
action_command: ~/klippy-env/bin/python3 ~/katapult/scripts/flashtool.py -d /dev/serial/by-id/usb-katapult_stm32h723xx_2F0005001751333031373837-if00

#Toolhead Board MCU
[toolhead_h36]
klipper_section: mcu H36Can
action_command: ~/klippy-env/bin/python3 ~/katapult/scripts/flashtool.py -u dcfc08b5ac16

#EMU MCUs
[emu_0]
klipper_section: mcu emu_0
action_command: ~/klippy-env/bin/python3 ~/katapult/scripts/flashtool.py -u d3e11d6444cf

[emu_1]
klipper_section: mcu emu_1
action_command: ~/klippy-env/bin/python3 ~/katapult/scripts/flashtool.py -u b1b82b5e3857
